// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALximu4gFC-MPhA2ZRzKvkAxE_PxM1pJM',
    appId: '1:595205438160:web:e3dd0de3373e38dffd3cd5',
    messagingSenderId: '595205438160',
    projectId: 'crudtutorial-2203d',
    authDomain: 'crudtutorial-2203d.firebaseapp.com',
    storageBucket: 'crudtutorial-2203d.appspot.com',
    measurementId: 'G-JY987RYTEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSI_CHgCFIH9Tgxhq0B9tJrCEcMrY_pcA',
    appId: '1:595205438160:android:d91659c29da73fe4fd3cd5',
    messagingSenderId: '595205438160',
    projectId: 'crudtutorial-2203d',
    storageBucket: 'crudtutorial-2203d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQX8IM2NRvZCVwJlZO_OOyidn4m3bgHRI',
    appId: '1:595205438160:ios:c64142ed30c7ac2afd3cd5',
    messagingSenderId: '595205438160',
    projectId: 'crudtutorial-2203d',
    storageBucket: 'crudtutorial-2203d.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQX8IM2NRvZCVwJlZO_OOyidn4m3bgHRI',
    appId: '1:595205438160:ios:0708ad1d49607adbfd3cd5',
    messagingSenderId: '595205438160',
    projectId: 'crudtutorial-2203d',
    storageBucket: 'crudtutorial-2203d.appspot.com',
    iosBundleId: 'com.example.crud.RunnerTests',
  );
}
